### ISSUE TITLE
agat_sp_manage_functional_annotation gene names

### ISSUE THREAD

**Issue by ctxchris** [NBISweden/AGAT#192] opened 2021-11-08 15:27 UTC
Hi,

I use Interpro results and BLAST hits to Uniprot to add functional annotation to a GFF3 file. In some cases the "Name" in the GFF3 matches the "GN" tag in the UniProt database, e.g. for "H671_2g6121".
GFF3:
> Chrom2	anno	gene	309686	313855	.	+	.	ID=G00000000053;Name=**h671_2g6121**;makerName=G00000000053
> Chrom2	anno	mRNA	509686	513855	.	+	.	ID=M00000000049;Parent=G00000000053;Name=h671_2g6121;makerName=M00000000049;product=von Willebrand factor A domain-containing protein 1;uniprot_id=A0A061IKS4

UniProt entry:
>tr|A0A061IKS4|A0A061IKS4_CRIGR von Willebrand factor A domain-containing protein 1 OS=Cricetulus griseus OX=10029 GN=H671_2g6121 PE=4 SV=1

In other cases, "Name" doesn't match the database entry, e.g. for UniProt "GN=CgPICR_008299", the name in the GFF3 is "cgpicr_10378". There is only one "A0A3L7HIV4" entry in the database and no entry for "cgpicr_10378". 
> Chrom3	anno	gene	128322495	128323187	.	-	.	ID=G00000029199;Name=**cgpicr_10378**;makerName=G00000029199
> Chrom3	anno	mRNA	128322495	128323187	.	-	.	ID=M00000023075;Parent=G00000029199;Name=cgpicr_10378;makerName=M00000023056;product=Condensin-2 complex subunit H2;uniprot_id=A0A3L7HIV4

> tr|A0A3L7HIV4|A0A3L7HIV4_CRIGR Condensin-2 complex subunit H2 OS=Cricetulus griseus OX=10029 GN=CgPICR_008299 PE=4 SV=1

Thanks,
Chris

**Comment by Juke34** [comment] 2021-11-08 16:19
Hi, which AGAT version are you using?

**Comment by ctxchris** [comment] 2021-11-09 07:52
bioconda version 0.8.0

**Comment by ctxchris** [comment] 2021-11-09 09:08
The wrong gene names also change.
E.g. for this UniProt entry:
> tr|G3HCE4|G3HCE4_CRIGR Alpha-(1,6)-fucosyltransferase OS=Cricetulus griseus OX=10029 GN=I79_008153 PE=3 SV=1

the gene names in the GFF3 differ from run to run: "i79_13", "i79_4403",  "i79_5566"

**Comment by LucileSol** [comment] 2021-11-09 09:23
No I have never seen that... 
What I have seen is if you have several genes being annotated with the same gene name then you will have for instance Name=fim1_1, Name=fin1_2, Name=fim1_3 ... with the original name being fim1. 
@ctxchris Are those gene names used several time?  and if yes @Juke34 could it be then a problem of the script handeling what is after the _

**Comment by Juke34** [comment] 2021-11-09 09:25
Might be due to protein with same score, AGAT will take one randomly. In such case we can improve to sort the result by name to at least have reproducible result.
I'm more afraid about the case where you don't see any entry for `cgpicr_10378`... did you check with case insensitive? (grep -i)


> could it be then a problem of the script handeling what is after the _
It might be, I will investigate.

@ctxchris could you send me over the data?

**Comment by ctxchris** [comment] 2021-11-09 11:45
In the cases I've looked at, there is always only a single gene copy in the genome. I.e. uniprot ID G3HCE4 is only present once in the GFF3 file.  I filtered the BLAST file beforehand for the best hit, so there is only one entry for each protein in the BLAST file that goes into AGAT. 
I did a case-insensitive search, but none of the wrong ID exist in the UniProt database, they the number part of the always start with "0": "CgPICR_0...", "I79_0..."

I did another run and "cgpicr_10378 changed to "cgpicr_6237", and i79_"5566" to "i79_5311"

**Comment by Juke34** [comment] 2021-11-09 12:55
Then @LucileSol is right, the gene name is `i79` and the `_XXX` is appended by AGAT to make the name uniq. It means there are other genes called `i79`. But I'm suprised by the high value, it should be incremented only if a gene has the same name, it sounds it is incremented at all round for all gene names.

**Comment by ctxchris** [comment] 2021-11-09 13:12
As every gene has a unique ID, it shouldn't matter if several genes have the same name.

**Comment by ctxchris** [comment] 2021-11-09 13:31
Here's an example of a protein occurring twice in the genome:
BLAST
> M00000039720	tr|A0A061HU94|A0A061HU94_CRIGR	93.3	477	1	1	1	446	1	477	3.84e-300	860
> M00000039726	tr|A0A061HU94|A0A061HU94_CRIGR	98.2	740	6	1	30	762	891	1630	0.0	1429

UniProt
> tr|A0A061HTC8|A0A061HTC8_CRIGR Hyaluronan synthase 3 OS=Cricetulus griseus OX=10029 GN=H671_21669 PE=4 SV=1

GFF3
> Chrom6	anno	gene	118092154	118098095	.	+	.	ID=choSartG00000050119;Name=h671_xg20583
> Chrom6	anno	mRNA	118092154	118098095	.	+	.	ID=M00000039720;Parent=G00000050119;Name=h671_xg20583;product=Voltage-dependent L-type calcium channel subunit alpha;uniprot_id=A0A061HU94

The second copy get's an "_2" attached to the name. But the name itself is wrong. The gene name can occur twice in the GFF, so there's no need to attach "_2".

> Chrom6	anno	gene	118108977	118119341	.	+	.	ID=choSartG00000050125;Name=h671_xg20583_2
Chrom6	anno	mRNA	118108977	118119341	.	+	.	ID=M00000039726;Parent=G00000050125;Name=h671_xg20583_2;product=Voltage-dependent L-type calcium channel subunit alpha;uniprot_id=A0A061HU94

**Comment by Juke34** [comment] 2021-11-09 15:28
Could you check how many times occurs `Name=h671` in  your output file?

**Comment by ctxchris** [comment] 2021-11-09 15:37
There are 3309 genes with Name=h671*

**Comment by ctxchris** [comment] 2021-11-09 16:29
Thank you

**Comment by Juke34** [comment] 2021-11-10 15:13
You can try the fix in the branch `192` following this protocol:
https://agat.readthedocs.io/en/latest/troubleshooting.html#how-to-use-a-version-of-agat-from-a-specific-branch

FYI: If isoforms catch different gene names (isoform1 => NameA, isoform2 => NameX), the gene feature will have all of them (Name=NameA,NameX). The Name attribute in the gene feature can contain a list of name. In the previous version, they were concatenated with "_" to create a unique string. 
For the mRNA features it does not change anything.

**Comment by ctxchris** [comment] 2021-11-11 10:49
Hi Jaques, it seems to work just fine. In all the cases I've looked at, the gene names are as in the database.

Thanks a lot
Chris

**Comment by Juke34** [comment] 2021-11-16 18:59
Fixed by PR #194. Now merged in Master

**Closed by Juke34** 2021-11-16 18:59 UTC
